### ISSUE TITLE
Is it possible to limit download/upload speed?

### ISSUE THREAD

**Issue by xhh** [mafintosh/peer-wire-protocol#5]
And how to do it if it is?

Thanks.

**Comment by nevercast** [comment]
I realise this is a very old issue, but I'll drop a reply here anyway.

I've not tested or even used peer-wire-protocol myself, but looking through the code you should be able to manually choke when the speed is greater than your limit. Something like the following might work:
```
var uploadLimit = 5000;

wire.on('request', function(pieceIndex, offset, length, callback) {
    if( wire.uploadSpeed > uploadLimit) {
      callback('Speed Limit');
    } else {
      // Get the piece to send
      callback(null, piece);
    }
});
```

I'm not sure how healthy this is protocol wise as you don't announce that you're actually choking the peer. All you are doing is ignoring their request. 

I don't know the rules of peer-wire protocol well enough to suggest a better implementation. 
@mafintosh will likely have a better idea how to do it.

**Comment by mafintosh** [comment]
@nevercast instead of callbacking with an error you'd probably wanna wait to call the callback until `uploadSpeed < uploadLimit`

**Comment by nevercast** [comment]
I noticed than when an error is provided it just returns and so you could never invoke the callback at all and it would do the same as the bittorrent spec doesn't say a reply is required and can be ignored

Its probably best to return immediately or as you suggest callback when uploadspeed is less than the limit.

One thing that should be done is a choke should be sent to the peer if they are going to be capped for a certain amount of time so they don't keep sending requests. 

I'm not sure of an implementation that will work cleanly

**Comment by mafintosh** [comment]
@nevercast we probably need to add that logic in [torrent-stream](https://github.com/mafintosh/torrent-stream) instead. If you're up for it you should open an issue/pr there

**Comment by mafintosh** [comment]
Closing it here as it should be fixed in torrent-stream as i mentioned. @xhh feel free to reopen the issue there. Would love to get this fixed :)

**Comment by nevercast** [comment]
Yes, https://github.com/mafintosh/torrent-stream feels like the correct place for this logic. This API should remain minimal.

I'll consider opening a PR. :)

**Comment by dcerisano** [comment]
There is a solution here which prevents download floods and sets a minimum rate limit.
https://github.com/mafintosh/torrent-stream/pull/122
A complete solution would also set a maximum rate limit.
This can be done by assuming 16K per request, and limiting the number of requests.
