### ISSUE TITLE
Wrap bncode.decode calls in try catch blocks

### ISSUE THREAD

**Issue by bsuh** [mafintosh/peer-wire-protocol#9]
index-0 (err): Error: uneven number of keys and values A
index-0 (err):     at cb_end (/home/app/torrent-server/node_modules/torrent-stream/node_modules/bncode/bncode.js:292:19)
index-0 (err):     at BdecodeSMachine.parse (/home/app/torrent-server/node_modules/torrent-stream/node_modules/bncode/bncode.js:166:17)
index-0 (err):     at Bdecode.decode (/home/app/torrent-server/node_modules/torrent-stream/node_modules/bncode/bncode.js:322:14)
index-0 (err):     at Object.decode (/home/app/torrent-server/node_modules/torrent-stream/node_modules/bncode/bncode.js:444:11)
index-0 (err):     at null.<anonymous> (/home/app/torrent-server/node_modules/torrent-stream/lib/exchange-metadata.js:22:23)
index-0 (err):     at g (events.js:199:16)
index-0 (err):     at emit (events.js:110:17)
index-0 (err):     at Wire._onextended (/home/app/torrent-server/node_modules/torrent-stream/node_modules/peer-wire-swarm/node_modules/peer-wire-protocol/index.js:306:7)
index-0 (err):     at onmessage (/home/app/torrent-server/node_modules/torrent-stream/node_modules/peer-wire-swarm/node_modules/peer-wire-protocol/index.js:112:16)
index-0 (err):     at Wire._write (/home/app/torrent-server/node_modules/torrent-stream/node_modules/peer-wire-swarm/node_modules/peer-wire-protocol/index.js:355:8)

**Comment by mafintosh** [comment]
If you send me a PR that fixes this I'll merge it :)

**Comment by bsuh** [comment]
Oops. Wrong project.
